[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/pubu/victor-hugo"

[context.deploy-preview]
  command = "npm run build-preview"
