[build]
  command = "make build && hugo"
  functions = "functions"
  publish = "public"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/pubu/test-hugo"
